# Generated by Django 3.2 on 2023-04-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0002_auto_20230430_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
